//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace NewSum_WinStore_ServiceProxy.NewSumFreeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", ConfigurationName="NewSumFreeService.NewSumFreeService")]
    internal interface NewSumFreeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getSepar" +
            "atorRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getSepar" +
            "atorResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorResponse> getSeparatorAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getCateg" +
            "oriesRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getCateg" +
            "oriesResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesResponse> getCategoriesAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getSente" +
            "nceSeparatorRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getSente" +
            "nceSeparatorResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorResponse> getSentenceSeparatorAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getCateg" +
            "orySourcesRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getCateg" +
            "orySourcesResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesResponse> getCategorySourcesAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "TitlesRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "TitlesResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesResponse> getTopicTitlesAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getSumma" +
            "ryRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getSumma" +
            "ryResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryResponse> getSummaryAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "TitlesByIDsRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "TitlesByIDsResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsResponse> getTopicTitlesByIDsAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "TitlesByIDRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "TitlesByIDResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDResponse> getTopicTitlesByIDAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "IDsRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "IDsResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsResponse> getTopicIDsAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "IDsByKeywordRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getTopic" +
            "IDsByKeywordResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordResponse> getTopicIDsByKeywordAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getLinkL" +
            "abelsRequest", ReplyAction="http://NewSumFreeService.Server.NewSumServer.scify.org/NewSumFreeService/getLinkL" +
            "abelsResponse")]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsResponse> getLinkLabelsAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getSeparatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSeparator", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorRequestBody Body;
        
        public getSeparatorRequest() {
        }
        
        public getSeparatorRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class getSeparatorRequestBody {
        
        public getSeparatorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getSeparatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSeparatorResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorResponseBody Body;
        
        public getSeparatorResponse() {
        }
        
        public getSeparatorResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getSeparatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getSeparatorResponseBody() {
        }
        
        public getSeparatorResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCategories", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesRequestBody Body;
        
        public getCategoriesRequest() {
        }
        
        public getCategoriesRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getCategoriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserSources;
        
        public getCategoriesRequestBody() {
        }
        
        public getCategoriesRequestBody(string sUserSources) {
            this.sUserSources = sUserSources;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCategoriesResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesResponseBody Body;
        
        public getCategoriesResponse() {
        }
        
        public getCategoriesResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCategoriesResponseBody() {
        }
        
        public getCategoriesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getSentenceSeparatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSentenceSeparator", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorRequestBody Body;
        
        public getSentenceSeparatorRequest() {
        }
        
        public getSentenceSeparatorRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class getSentenceSeparatorRequestBody {
        
        public getSentenceSeparatorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getSentenceSeparatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSentenceSeparatorResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorResponseBody Body;
        
        public getSentenceSeparatorResponse() {
        }
        
        public getSentenceSeparatorResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getSentenceSeparatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getSentenceSeparatorResponseBody() {
        }
        
        public getSentenceSeparatorResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getCategorySourcesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCategorySources", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesRequestBody Body;
        
        public getCategorySourcesRequest() {
        }
        
        public getCategorySourcesRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getCategorySourcesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCategory;
        
        public getCategorySourcesRequestBody() {
        }
        
        public getCategorySourcesRequestBody(string sCategory) {
            this.sCategory = sCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getCategorySourcesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCategorySourcesResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesResponseBody Body;
        
        public getCategorySourcesResponse() {
        }
        
        public getCategorySourcesResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getCategorySourcesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCategorySourcesResponseBody() {
        }
        
        public getCategorySourcesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicTitlesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicTitles", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesRequestBody Body;
        
        public getTopicTitlesRequest() {
        }
        
        public getTopicTitlesRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicTitlesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserSources;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sCategory;
        
        public getTopicTitlesRequestBody() {
        }
        
        public getTopicTitlesRequestBody(string sUserSources, string sCategory) {
            this.sUserSources = sUserSources;
            this.sCategory = sCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicTitlesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicTitlesResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesResponseBody Body;
        
        public getTopicTitlesResponse() {
        }
        
        public getTopicTitlesResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicTitlesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTopicTitlesResponseBody() {
        }
        
        public getTopicTitlesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getSummaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSummary", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryRequestBody Body;
        
        public getSummaryRequest() {
        }
        
        public getSummaryRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getSummaryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTopicID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUserSources;
        
        public getSummaryRequestBody() {
        }
        
        public getSummaryRequestBody(string sTopicID, string sUserSources) {
            this.sTopicID = sTopicID;
            this.sUserSources = sUserSources;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getSummaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSummaryResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryResponseBody Body;
        
        public getSummaryResponse() {
        }
        
        public getSummaryResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getSummaryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getSummaryResponseBody() {
        }
        
        public getSummaryResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicTitlesByIDsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicTitlesByIDs", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsRequestBody Body;
        
        public getTopicTitlesByIDsRequest() {
        }
        
        public getTopicTitlesByIDsRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicTitlesByIDsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTopicIDs;
        
        public getTopicTitlesByIDsRequestBody() {
        }
        
        public getTopicTitlesByIDsRequestBody(string sTopicIDs) {
            this.sTopicIDs = sTopicIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicTitlesByIDsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicTitlesByIDsResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsResponseBody Body;
        
        public getTopicTitlesByIDsResponse() {
        }
        
        public getTopicTitlesByIDsResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicTitlesByIDsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTopicTitlesByIDsResponseBody() {
        }
        
        public getTopicTitlesByIDsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicTitlesByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicTitlesByID", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDRequestBody Body;
        
        public getTopicTitlesByIDRequest() {
        }
        
        public getTopicTitlesByIDRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicTitlesByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTopicID;
        
        public getTopicTitlesByIDRequestBody() {
        }
        
        public getTopicTitlesByIDRequestBody(string sTopicID) {
            this.sTopicID = sTopicID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicTitlesByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicTitlesByIDResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDResponseBody Body;
        
        public getTopicTitlesByIDResponse() {
        }
        
        public getTopicTitlesByIDResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicTitlesByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTopicTitlesByIDResponseBody() {
        }
        
        public getTopicTitlesByIDResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicIDsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicIDs", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsRequestBody Body;
        
        public getTopicIDsRequest() {
        }
        
        public getTopicIDsRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicIDsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUserSources;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sCategory;
        
        public getTopicIDsRequestBody() {
        }
        
        public getTopicIDsRequestBody(string sUserSources, string sCategory) {
            this.sUserSources = sUserSources;
            this.sCategory = sCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicIDsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicIDsResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsResponseBody Body;
        
        public getTopicIDsResponse() {
        }
        
        public getTopicIDsResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicIDsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTopicIDsResponseBody() {
        }
        
        public getTopicIDsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicIDsByKeywordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicIDsByKeyword", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordRequestBody Body;
        
        public getTopicIDsByKeywordRequest() {
        }
        
        public getTopicIDsByKeywordRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicIDsByKeywordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sKeyword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sUserSources;
        
        public getTopicIDsByKeywordRequestBody() {
        }
        
        public getTopicIDsByKeywordRequestBody(string sKeyword, string sUserSources) {
            this.sKeyword = sKeyword;
            this.sUserSources = sUserSources;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getTopicIDsByKeywordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopicIDsByKeywordResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordResponseBody Body;
        
        public getTopicIDsByKeywordResponse() {
        }
        
        public getTopicIDsByKeywordResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getTopicIDsByKeywordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTopicIDsByKeywordResponseBody() {
        }
        
        public getTopicIDsByKeywordResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getLinkLabelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLinkLabels", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsRequestBody Body;
        
        public getLinkLabelsRequest() {
        }
        
        public getLinkLabelsRequest(NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class getLinkLabelsRequestBody {
        
        public getLinkLabelsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getLinkLabelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLinkLabelsResponse", Namespace="http://NewSumFreeService.Server.NewSumServer.scify.org/", Order=0)]
        public NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsResponseBody Body;
        
        public getLinkLabelsResponse() {
        }
        
        public getLinkLabelsResponse(NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class getLinkLabelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getLinkLabelsResponseBody() {
        }
        
        public getLinkLabelsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface NewSumFreeServiceChannel : NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class NewSumFreeServiceClient : System.ServiceModel.ClientBase<NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService>, NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NewSumFreeServiceClient() : 
                base(NewSumFreeServiceClient.GetDefaultBinding(), NewSumFreeServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.NewSumFreeServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NewSumFreeServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NewSumFreeServiceClient.GetBindingForEndpoint(endpointConfiguration), NewSumFreeServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NewSumFreeServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NewSumFreeServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NewSumFreeServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NewSumFreeServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NewSumFreeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getSeparatorAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorRequest request) {
            return base.Channel.getSeparatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorResponse> getSeparatorAsync() {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getSeparatorRequestBody();
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getSeparatorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getCategoriesAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesRequest request) {
            return base.Channel.getCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesResponse> getCategoriesAsync(string sUserSources) {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategoriesRequestBody();
            inValue.Body.sUserSources = sUserSources;
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getSentenceSeparatorAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorRequest request) {
            return base.Channel.getSentenceSeparatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorResponse> getSentenceSeparatorAsync() {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getSentenceSeparatorRequestBody();
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getSentenceSeparatorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getCategorySourcesAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesRequest request) {
            return base.Channel.getCategorySourcesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesResponse> getCategorySourcesAsync(string sCategory) {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getCategorySourcesRequestBody();
            inValue.Body.sCategory = sCategory;
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getCategorySourcesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getTopicTitlesAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesRequest request) {
            return base.Channel.getTopicTitlesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesResponse> getTopicTitlesAsync(string sUserSources, string sCategory) {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesRequestBody();
            inValue.Body.sUserSources = sUserSources;
            inValue.Body.sCategory = sCategory;
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getTopicTitlesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getSummaryAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryRequest request) {
            return base.Channel.getSummaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryResponse> getSummaryAsync(string sTopicID, string sUserSources) {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getSummaryRequestBody();
            inValue.Body.sTopicID = sTopicID;
            inValue.Body.sUserSources = sUserSources;
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getSummaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getTopicTitlesByIDsAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsRequest request) {
            return base.Channel.getTopicTitlesByIDsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsResponse> getTopicTitlesByIDsAsync(string sTopicIDs) {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDsRequestBody();
            inValue.Body.sTopicIDs = sTopicIDs;
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getTopicTitlesByIDsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getTopicTitlesByIDAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDRequest request) {
            return base.Channel.getTopicTitlesByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDResponse> getTopicTitlesByIDAsync(string sTopicID) {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicTitlesByIDRequestBody();
            inValue.Body.sTopicID = sTopicID;
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getTopicTitlesByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getTopicIDsAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsRequest request) {
            return base.Channel.getTopicIDsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsResponse> getTopicIDsAsync(string sUserSources, string sCategory) {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsRequestBody();
            inValue.Body.sUserSources = sUserSources;
            inValue.Body.sCategory = sCategory;
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getTopicIDsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getTopicIDsByKeywordAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordRequest request) {
            return base.Channel.getTopicIDsByKeywordAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordResponse> getTopicIDsByKeywordAsync(string sKeyword, string sUserSources) {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getTopicIDsByKeywordRequestBody();
            inValue.Body.sKeyword = sKeyword;
            inValue.Body.sUserSources = sUserSources;
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getTopicIDsByKeywordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsResponse> NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService.getLinkLabelsAsync(NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsRequest request) {
            return base.Channel.getLinkLabelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsResponse> getLinkLabelsAsync() {
            NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsRequest inValue = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsRequest();
            inValue.Body = new NewSum_WinStore_ServiceProxy.NewSumFreeService.getLinkLabelsRequestBody();
            return ((NewSum_WinStore_ServiceProxy.NewSumFreeService.NewSumFreeService)(this)).getLinkLabelsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.NewSumFreeServicePort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.NewSumFreeServicePort)) {
                return new System.ServiceModel.EndpointAddress("http://143.233.226.97:28080/NewSumFreeService/NewSumFreeService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return NewSumFreeServiceClient.GetBindingForEndpoint(EndpointConfiguration.NewSumFreeServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return NewSumFreeServiceClient.GetEndpointAddress(EndpointConfiguration.NewSumFreeServicePort);
        }
        
        public enum EndpointConfiguration {
            
            NewSumFreeServicePort,
        }
    }
}
